services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: labs
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 1@test.com
      PGADMIN_DEFAULT_PASSWORD: 1
    ports:
      - "8080:80"
    depends_on:
      - postgres
    # том для pgadmin не используется (чтобы избежать проблем с правами)

volumes:
  postgres_data:
